// =====================================================
// Nawaqes — Android build.gradle (Project-level)
// =====================================================

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.2'
        classpath 'com.google.gms:google-services:4.4.2'
    }
}

apply plugin: 'com.android.application'

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
